name: Burning CI

on: [push, pull_request, workflow_dispatch]

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12', '14', '16']
      fail-fast: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm i
    - name: Run build
      run: npm run build
      env:
        CI: true
    - name: Upload result
      if: matrix.node-version == '16'
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12', '14', '16']
      fail-fast: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm i
    - name: Run unit tests
      run: npm run test
      env:
        CI: true

  docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm i
    - name: Generate docs
      run: npm run doc
      env:
        CI: true
    - name: Upload result
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [compile, test, docs]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: deploy
        fetch-depth: 0
    - name: Setup git
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    - name: Download Artifacts
      uses: actions/download-artifact@v2
    - name: Copy main files
      run: |
        cp -fv dist/main.js docs/burning-brackets.js
        cp -fv dist/main.js docs/burning-brackets.min.js
    - name: Commit update
      run: |
        git add docs
        git add dist
        git commit -m "Update $(date)"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: deploy
